### ISSUE TITLE
Cannot compile projog even though projogGeneratedClasses folder has been created and added to build path and runtime path

### ISSUE THREAD

**Issue by mkoslowski-metis** [s-webber/projog#118] opened 2018-07-10 15:50 UTC
Hello, 
I apologize in advance if this issue has already been addressed or if I should have posted this somewhere else.

When trying to make a projog object consult a file in an eclipse java environment, I receive the following error:

"Cannot compile: org.projog.content_generated_at_runtime.CompiledPredicate2 using classpath:"
Followed by all of the paths of the libraries and jars I use separated by semicolons. The last element in the classpath is the location of the projogGeneratedClasses folder with no  slash or semicolon afterwards.

I also see a null pointer exception coming from line 55 in the JavaSourceCompiler, which I think means the Locale.getDefault() method is returning null.

Please let me know if you have any advice on how to solve this problem.

Thanks.

**Comment by s-webber** [comment] 2018-07-14 15:49
Hello,

Thank you for raising this issue. I am not sure what the cause of this issue could be.

It is interesting that you suspect the `NullPointerException` is because `Locale.getDefault()` is returning `null`. To help determine if this is the cause can you please try, before creating the Projog object, ensuring the default locale is set by calling:

```
java.util.Locale.setDefault(java.util.Locale.ENGLISH);
```

To help me investigate this further can you please provide me with the full stacktrace of the `NullPointerException` you are seeing?

Incidentally, I have created the following GitHub project which provides examples of calling Projog from Java. I wonder if these examples will work for you if you try to run them in Eclipse:

https://github.com/s-webber/projog-example

Thanks.

**Comment by s-webber** [comment] 2018-08-12 15:01
Hello,

Since this issue was raised there has been a change made to how Projog compiles code at runtime (#120). Projog no longer writes Java code generated at runtime to the filesystem, and no longer requires the `projogGeneratedClasses` directory to be in the classpath. As part of making this change a `Locale` is now specified in `JavaSourceCompiler`, rather than relying on the default locale.

I would be interested to know if you still see the problem mentioned in the description of this issue when you use the latest version of Projog, which is now available as a Maven artifact:

```
<dependency>
   <groupId>org.projog</groupId>
   <artifactId>projog-core</artifactId>
   <version>0.2.0</version>
</dependency>
```

If this is still a problem then please update this issue with more details, so I can investigate it further. Alternatively, if you are having any other problems using Projog (or you have a suggestion for an enhancement) then please raise a new issue.

Thanks.

**Comment by s-webber** [comment] 2019-02-02 11:34
Thank you for raising this issue. I am closing this issue as I have not been able to reproduce the problem and since is was raised there have been a number of changes to Projog which may of altered this behaviour.

If you are still having this problem after upgrading to the latest version of Projog then please add another comment to this issue with more detail. I will then investigate further.

**Closed by s-webber** 2019-02-02 11:34 UTC
Labels: bug
